from domain.entities import TypeMapping


FIREBIRD_TO_POSTGRES: dict[str, TypeMapping] = {
    "SMALLINT": TypeMapping("SMALLINT", "SMALLINT"),
    "INTEGER": TypeMapping("INTEGER", "INTEGER"),
    "BIGINT": TypeMapping("BIGINT", "BIGINT"),
    "FLOAT": TypeMapping("FLOAT", "REAL"),
    "DOUBLE PRECISION": TypeMapping("DOUBLE PRECISION", "DOUBLE PRECISION"),
    "DECIMAL": TypeMapping("DECIMAL", "DECIMAL"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMERIC"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "BLOB SUB_TYPE TEXT": TypeMapping("BLOB SUB_TYPE TEXT", "TEXT"),
    "BLOB SUB_TYPE 0": TypeMapping("BLOB SUB_TYPE 0", "BYTEA", warning="Campo binário — verificar necessidade de migração"),
    "BLOB": TypeMapping("BLOB", "BYTEA", warning="Tipo binário — verificar conteúdo"),
    "DATE": TypeMapping("DATE", "DATE"),
    "TIME": TypeMapping("TIME", "TIME"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TIMESTAMP"),
    "BOOLEAN": TypeMapping("BOOLEAN", "BOOLEAN"),
}

ORACLE_TO_MARIADB: dict[str, TypeMapping] = {
    "VARCHAR2": TypeMapping("VARCHAR2", "VARCHAR"),
    "NVARCHAR2": TypeMapping("NVARCHAR2", "VARCHAR", conversion_expr="CAST(%s AS VARCHAR)", warning="Perda de codificação NVARCHAR"),
    "CLOB": TypeMapping("CLOB", "LONGTEXT"),
    "NCLOB": TypeMapping("NCLOB", "TEXT", warning="Perda de codificação NCLOB"),
    "BLOB": TypeMapping("BLOB", "LONGBLOB"),
    "RAW": TypeMapping("RAW", "VARBINARY"),
    "NUMBER": TypeMapping("NUMBER", "DECIMAL", warning="NUMBER sem precisão — definir DECIMAL(38) ou BIGINT"),
    "FLOAT": TypeMapping("FLOAT", "DOUBLE"),
    "DATE": TypeMapping("DATE", "DATETIME", warning="Oracle DATE contém hora — mapeado para DATETIME"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TIMESTAMP"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "LONG": TypeMapping("LONG", "LONGTEXT", warning="LONG obsoleto — revisar uso"),
}

MSSQL_TO_POSTGRES: dict[str, TypeMapping] = {
    "INT": TypeMapping("INT", "INTEGER"),
    "BIGINT": TypeMapping("BIGINT", "BIGINT"),
    "SMALLINT": TypeMapping("SMALLINT", "SMALLINT"),
    "TINYINT": TypeMapping("TINYINT", "SMALLINT", warning="TINYINT (0-255) → SMALLINT"),
    "BIT": TypeMapping("BIT", "BOOLEAN"),
    "DECIMAL": TypeMapping("DECIMAL", "DECIMAL"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMERIC"),
    "MONEY": TypeMapping("MONEY", "NUMERIC", conversion_expr="CAST(%s AS NUMERIC(19,4))"),
    "SMALLMONEY": TypeMapping("SMALLMONEY", "NUMERIC", conversion_expr="CAST(%s AS NUMERIC(10,4))"),
    "FLOAT": TypeMapping("FLOAT", "DOUBLE PRECISION"),
    "REAL": TypeMapping("REAL", "REAL"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "NVARCHAR": TypeMapping("NVARCHAR", "VARCHAR"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "NCHAR": TypeMapping("NCHAR", "CHAR"),
    "TEXT": TypeMapping("TEXT", "TEXT"),
    "NTEXT": TypeMapping("NTEXT", "TEXT", warning="NTEXT → TEXT (perda de Unicode)"),
    "DATE": TypeMapping("DATE", "DATE"),
    "TIME": TypeMapping("TIME", "TIME"),
    "DATETIME": TypeMapping("DATETIME", "TIMESTAMP"),
    "DATETIME2": TypeMapping("DATETIME2", "TIMESTAMP"),
    "SMALLDATETIME": TypeMapping("SMALLDATETIME", "TIMESTAMP"),
    "DATETIMEOFFSET": TypeMapping("DATETIMEOFFSET", "TIMESTAMPTZ"),
    "UNIQUEIDENTIFIER": TypeMapping("UNIQUEIDENTIFIER", "UUID"),
    "IMAGE": TypeMapping("IMAGE", "BYTEA", warning="IMAGE → BYTEA"),
    "VARBINARY": TypeMapping("VARBINARY", "BYTEA"),
    "BINARY": TypeMapping("BINARY", "BYTEA"),
    "ROWVERSION": TypeMapping("ROWVERSION", "BYTEA", warning="ROWVERSION — semântica diferente no PostgreSQL"),
    "SQL_VARIANT": TypeMapping("SQL_VARIANT", "TEXT", warning="SQL_VARIANT → TEXT (perda de tipo)"),
    "XML": TypeMapping("XML", "XML"),
    "GEOGRAPHY": TypeMapping("GEOGRAPHY", "TEXT", warning="GEOGRAPHY — requer conversão manual"),
    "GEOMETRY": TypeMapping("GEOMETRY", "TEXT", warning="GEOMETRY — requer conversão manual"),
    "HIERARCHYID": TypeMapping("HIERARCHYID", "TEXT", warning="HIERARCHYID — requer conversão manual"),
}

FIREBIRD_TO_MYSQL: dict[str, TypeMapping] = {
    "SMALLINT": TypeMapping("SMALLINT", "SMALLINT"),
    "INTEGER": TypeMapping("INTEGER", "INT"),
    "BIGINT": TypeMapping("BIGINT", "BIGINT"),
    "FLOAT": TypeMapping("FLOAT", "FLOAT"),
    "DOUBLE PRECISION": TypeMapping("DOUBLE PRECISION", "DOUBLE"),
    "DECIMAL": TypeMapping("DECIMAL", "DECIMAL"),
    "NUMERIC": TypeMapping("NUMERIC", "DECIMAL"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "BLOB SUB_TYPE TEXT": TypeMapping("BLOB SUB_TYPE TEXT", "LONGTEXT"),
    "BLOB SUB_TYPE 0": TypeMapping("BLOB SUB_TYPE 0", "LONGBLOB", warning="Campo binário — verificar necessidade de migração"),
    "BLOB": TypeMapping("BLOB", "LONGBLOB", warning="Tipo binário — verificar conteúdo"),
    "DATE": TypeMapping("DATE", "DATE"),
    "TIME": TypeMapping("TIME", "TIME"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "DATETIME"),
    "BOOLEAN": TypeMapping("BOOLEAN", "TINYINT(1)"),
}

FIREBIRD_TO_MARIADB: dict[str, TypeMapping] = FIREBIRD_TO_MYSQL

FIREBIRD_TO_MSSQL: dict[str, TypeMapping] = {
    "SMALLINT": TypeMapping("SMALLINT", "SMALLINT"),
    "INTEGER": TypeMapping("INTEGER", "INT"),
    "BIGINT": TypeMapping("BIGINT", "BIGINT"),
    "FLOAT": TypeMapping("FLOAT", "FLOAT"),
    "DOUBLE PRECISION": TypeMapping("DOUBLE PRECISION", "FLOAT"),
    "DECIMAL": TypeMapping("DECIMAL", "DECIMAL"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMERIC"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "BLOB SUB_TYPE TEXT": TypeMapping("BLOB SUB_TYPE TEXT", "VARCHAR(MAX)"),
    "BLOB SUB_TYPE 0": TypeMapping("BLOB SUB_TYPE 0", "VARBINARY(MAX)", warning="Campo binário — verificar necessidade de migração"),
    "BLOB": TypeMapping("BLOB", "VARBINARY(MAX)", warning="Tipo binário — verificar conteúdo"),
    "DATE": TypeMapping("DATE", "DATE"),
    "TIME": TypeMapping("TIME", "TIME"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "DATETIME2"),
    "BOOLEAN": TypeMapping("BOOLEAN", "BIT"),
}

FIREBIRD_TO_ORACLE: dict[str, TypeMapping] = {
    "SMALLINT": TypeMapping("SMALLINT", "NUMBER(5)"),
    "INTEGER": TypeMapping("INTEGER", "NUMBER(10)"),
    "BIGINT": TypeMapping("BIGINT", "NUMBER(19)"),
    "FLOAT": TypeMapping("FLOAT", "BINARY_FLOAT"),
    "DOUBLE PRECISION": TypeMapping("DOUBLE PRECISION", "BINARY_DOUBLE"),
    "DECIMAL": TypeMapping("DECIMAL", "NUMBER"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMBER"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR2"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "BLOB SUB_TYPE TEXT": TypeMapping("BLOB SUB_TYPE TEXT", "CLOB"),
    "BLOB SUB_TYPE 0": TypeMapping("BLOB SUB_TYPE 0", "BLOB", warning="Campo binário — verificar necessidade de migração"),
    "BLOB": TypeMapping("BLOB", "BLOB", warning="Tipo binário — verificar conteúdo"),
    "DATE": TypeMapping("DATE", "DATE"),
    "TIME": TypeMapping("TIME", "INTERVAL DAY TO SECOND"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TIMESTAMP"),
    "BOOLEAN": TypeMapping("BOOLEAN", "NUMBER(1)"),
}

MSSQL_TO_MYSQL: dict[str, TypeMapping] = {
    "INT": TypeMapping("INT", "INT"),
    "BIGINT": TypeMapping("BIGINT", "BIGINT"),
    "SMALLINT": TypeMapping("SMALLINT", "SMALLINT"),
    "TINYINT": TypeMapping("TINYINT", "TINYINT"),
    "BIT": TypeMapping("BIT", "TINYINT(1)"),
    "DECIMAL": TypeMapping("DECIMAL", "DECIMAL"),
    "NUMERIC": TypeMapping("NUMERIC", "DECIMAL"),
    "MONEY": TypeMapping("MONEY", "DECIMAL(19,4)"),
    "SMALLMONEY": TypeMapping("SMALLMONEY", "DECIMAL(10,4)"),
    "FLOAT": TypeMapping("FLOAT", "DOUBLE"),
    "REAL": TypeMapping("REAL", "FLOAT"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "NVARCHAR": TypeMapping("NVARCHAR", "VARCHAR"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "NCHAR": TypeMapping("NCHAR", "CHAR"),
    "TEXT": TypeMapping("TEXT", "TEXT"),
    "NTEXT": TypeMapping("NTEXT", "LONGTEXT", warning="NTEXT → LONGTEXT (perda de Unicode)"),
    "DATE": TypeMapping("DATE", "DATE"),
    "TIME": TypeMapping("TIME", "TIME"),
    "DATETIME": TypeMapping("DATETIME", "DATETIME"),
    "DATETIME2": TypeMapping("DATETIME2", "DATETIME"),
    "SMALLDATETIME": TypeMapping("SMALLDATETIME", "DATETIME"),
    "DATETIMEOFFSET": TypeMapping("DATETIMEOFFSET", "VARCHAR(35)", warning="DATETIMEOFFSET → VARCHAR"),
    "UNIQUEIDENTIFIER": TypeMapping("UNIQUEIDENTIFIER", "CHAR(36)"),
    "IMAGE": TypeMapping("IMAGE", "LONGBLOB"),
    "VARBINARY": TypeMapping("VARBINARY", "VARBINARY"),
    "BINARY": TypeMapping("BINARY", "BINARY"),
    "SQL_VARIANT": TypeMapping("SQL_VARIANT", "TEXT", warning="SQL_VARIANT → TEXT (perda de tipo)"),
    "XML": TypeMapping("XML", "LONGTEXT"),
}

MSSQL_TO_MARIADB: dict[str, TypeMapping] = MSSQL_TO_MYSQL

MSSQL_TO_ORACLE: dict[str, TypeMapping] = {
    "INT": TypeMapping("INT", "NUMBER(10)"),
    "BIGINT": TypeMapping("BIGINT", "NUMBER(19)"),
    "SMALLINT": TypeMapping("SMALLINT", "NUMBER(5)"),
    "TINYINT": TypeMapping("TINYINT", "NUMBER(3)"),
    "BIT": TypeMapping("BIT", "NUMBER(1)"),
    "DECIMAL": TypeMapping("DECIMAL", "NUMBER"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMBER"),
    "MONEY": TypeMapping("MONEY", "NUMBER(19,4)"),
    "SMALLMONEY": TypeMapping("SMALLMONEY", "NUMBER(10,4)"),
    "FLOAT": TypeMapping("FLOAT", "BINARY_DOUBLE"),
    "REAL": TypeMapping("REAL", "BINARY_FLOAT"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR2"),
    "NVARCHAR": TypeMapping("NVARCHAR", "NVARCHAR2"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "NCHAR": TypeMapping("NCHAR", "NCHAR"),
    "TEXT": TypeMapping("TEXT", "CLOB"),
    "NTEXT": TypeMapping("NTEXT", "NCLOB", warning="NTEXT → NCLOB"),
    "DATE": TypeMapping("DATE", "DATE"),
    "TIME": TypeMapping("TIME", "INTERVAL DAY TO SECOND"),
    "DATETIME": TypeMapping("DATETIME", "TIMESTAMP"),
    "DATETIME2": TypeMapping("DATETIME2", "TIMESTAMP"),
    "SMALLDATETIME": TypeMapping("SMALLDATETIME", "TIMESTAMP"),
    "DATETIMEOFFSET": TypeMapping("DATETIMEOFFSET", "TIMESTAMP WITH TIME ZONE"),
    "UNIQUEIDENTIFIER": TypeMapping("UNIQUEIDENTIFIER", "RAW(16)"),
    "IMAGE": TypeMapping("IMAGE", "BLOB"),
    "VARBINARY": TypeMapping("VARBINARY", "BLOB"),
    "BINARY": TypeMapping("BINARY", "RAW"),
    "SQL_VARIANT": TypeMapping("SQL_VARIANT", "CLOB", warning="SQL_VARIANT → CLOB"),
    "XML": TypeMapping("XML", "XMLTYPE"),
}

ORACLE_TO_POSTGRES: dict[str, TypeMapping] = {
    "VARCHAR2": TypeMapping("VARCHAR2", "VARCHAR"),
    "NVARCHAR2": TypeMapping("NVARCHAR2", "VARCHAR"),
    "CLOB": TypeMapping("CLOB", "TEXT"),
    "NCLOB": TypeMapping("NCLOB", "TEXT", warning="NCLOB → TEXT (perda de codificação)"),
    "BLOB": TypeMapping("BLOB", "BYTEA"),
    "RAW": TypeMapping("RAW", "BYTEA"),
    "NUMBER": TypeMapping("NUMBER", "DECIMAL", warning="NUMBER sem precisão — definir DECIMAL(38) ou BIGINT"),
    "FLOAT": TypeMapping("FLOAT", "DOUBLE PRECISION"),
    "BINARY_FLOAT": TypeMapping("BINARY_FLOAT", "REAL"),
    "BINARY_DOUBLE": TypeMapping("BINARY_DOUBLE", "DOUBLE PRECISION"),
    "DATE": TypeMapping("DATE", "TIMESTAMP", warning="Oracle DATE contém hora — mapeado para TIMESTAMP"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TIMESTAMP"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "LONG": TypeMapping("LONG", "TEXT", warning="LONG obsoleto — revisar uso"),
    "XMLTYPE": TypeMapping("XMLTYPE", "XML"),
}

ORACLE_TO_MSSQL: dict[str, TypeMapping] = {
    "VARCHAR2": TypeMapping("VARCHAR2", "VARCHAR"),
    "NVARCHAR2": TypeMapping("NVARCHAR2", "NVARCHAR"),
    "CLOB": TypeMapping("CLOB", "VARCHAR(MAX)"),
    "NCLOB": TypeMapping("NCLOB", "NVARCHAR(MAX)", warning="NCLOB → NVARCHAR(MAX)"),
    "BLOB": TypeMapping("BLOB", "VARBINARY(MAX)"),
    "RAW": TypeMapping("RAW", "VARBINARY"),
    "NUMBER": TypeMapping("NUMBER", "DECIMAL", warning="NUMBER sem precisão — definir DECIMAL(38) ou BIGINT"),
    "FLOAT": TypeMapping("FLOAT", "FLOAT"),
    "BINARY_FLOAT": TypeMapping("BINARY_FLOAT", "FLOAT"),
    "BINARY_DOUBLE": TypeMapping("BINARY_DOUBLE", "FLOAT"),
    "DATE": TypeMapping("DATE", "DATETIME2", warning="Oracle DATE contém hora — mapeado para DATETIME2"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "DATETIME2"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "LONG": TypeMapping("LONG", "VARCHAR(MAX)", warning="LONG obsoleto — revisar uso"),
    "XMLTYPE": TypeMapping("XMLTYPE", "XML"),
}

POSTGRES_TO_MSSQL: dict[str, TypeMapping] = {
    "INTEGER": TypeMapping("INTEGER", "INT"),
    "BIGINT": TypeMapping("BIGINT", "BIGINT"),
    "SMALLINT": TypeMapping("SMALLINT", "SMALLINT"),
    "BOOLEAN": TypeMapping("BOOLEAN", "BIT"),
    "DECIMAL": TypeMapping("DECIMAL", "DECIMAL"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMERIC"),
    "REAL": TypeMapping("REAL", "REAL"),
    "DOUBLE PRECISION": TypeMapping("DOUBLE PRECISION", "FLOAT"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "TEXT": TypeMapping("TEXT", "VARCHAR(MAX)"),
    "DATE": TypeMapping("DATE", "DATE"),
    "TIME": TypeMapping("TIME", "TIME"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "DATETIME2"),
    "TIMESTAMPTZ": TypeMapping("TIMESTAMPTZ", "DATETIMEOFFSET"),
    "UUID": TypeMapping("UUID", "UNIQUEIDENTIFIER"),
    "BYTEA": TypeMapping("BYTEA", "VARBINARY(MAX)"),
    "XML": TypeMapping("XML", "XML"),
    "JSON": TypeMapping("JSON", "NVARCHAR(MAX)", warning="JSON → NVARCHAR(MAX)"),
    "JSONB": TypeMapping("JSONB", "NVARCHAR(MAX)", warning="JSONB → NVARCHAR(MAX)"),
}

POSTGRES_TO_MYSQL: dict[str, TypeMapping] = {
    "INTEGER": TypeMapping("INTEGER", "INT"),
    "BIGINT": TypeMapping("BIGINT", "BIGINT"),
    "SMALLINT": TypeMapping("SMALLINT", "SMALLINT"),
    "BOOLEAN": TypeMapping("BOOLEAN", "TINYINT(1)"),
    "DECIMAL": TypeMapping("DECIMAL", "DECIMAL"),
    "NUMERIC": TypeMapping("NUMERIC", "DECIMAL"),
    "REAL": TypeMapping("REAL", "FLOAT"),
    "DOUBLE PRECISION": TypeMapping("DOUBLE PRECISION", "DOUBLE"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "TEXT": TypeMapping("TEXT", "TEXT"),
    "DATE": TypeMapping("DATE", "DATE"),
    "TIME": TypeMapping("TIME", "TIME"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "DATETIME"),
    "TIMESTAMPTZ": TypeMapping("TIMESTAMPTZ", "VARCHAR(35)", warning="TIMESTAMPTZ → VARCHAR"),
    "UUID": TypeMapping("UUID", "CHAR(36)"),
    "BYTEA": TypeMapping("BYTEA", "BLOB"),
    "XML": TypeMapping("XML", "LONGTEXT"),
    "JSON": TypeMapping("JSON", "LONGTEXT"),
    "JSONB": TypeMapping("JSONB", "LONGTEXT"),
}

POSTGRES_TO_MARIADB: dict[str, TypeMapping] = POSTGRES_TO_MYSQL

POSTGRES_TO_ORACLE: dict[str, TypeMapping] = {
    "INTEGER": TypeMapping("INTEGER", "NUMBER(10)"),
    "BIGINT": TypeMapping("BIGINT", "NUMBER(19)"),
    "SMALLINT": TypeMapping("SMALLINT", "NUMBER(5)"),
    "BOOLEAN": TypeMapping("BOOLEAN", "NUMBER(1)"),
    "DECIMAL": TypeMapping("DECIMAL", "NUMBER"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMBER"),
    "REAL": TypeMapping("REAL", "BINARY_FLOAT"),
    "DOUBLE PRECISION": TypeMapping("DOUBLE PRECISION", "BINARY_DOUBLE"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR2"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "TEXT": TypeMapping("TEXT", "CLOB"),
    "DATE": TypeMapping("DATE", "DATE"),
    "TIME": TypeMapping("TIME", "INTERVAL DAY TO SECOND"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TIMESTAMP"),
    "TIMESTAMPTZ": TypeMapping("TIMESTAMPTZ", "TIMESTAMP WITH TIME ZONE"),
    "UUID": TypeMapping("UUID", "RAW(16)"),
    "BYTEA": TypeMapping("BYTEA", "BLOB"),
    "XML": TypeMapping("XML", "XMLTYPE"),
    "JSON": TypeMapping("JSON", "CLOB", warning="JSON → CLOB"),
    "JSONB": TypeMapping("JSONB", "CLOB", warning="JSONB → CLOB"),
}

SQLITE_TO_POSTGRES: dict[str, TypeMapping] = {
    "INTEGER": TypeMapping("INTEGER", "INTEGER"),
    "INT": TypeMapping("INT", "INTEGER"),
    "BIGINT": TypeMapping("BIGINT", "BIGINT"),
    "SMALLINT": TypeMapping("SMALLINT", "SMALLINT"),
    "TINYINT": TypeMapping("TINYINT", "SMALLINT"),
    "REAL": TypeMapping("REAL", "REAL"),
    "FLOAT": TypeMapping("FLOAT", "REAL"),
    "DOUBLE": TypeMapping("DOUBLE", "DOUBLE PRECISION"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMERIC"),
    "DECIMAL": TypeMapping("DECIMAL", "DECIMAL"),
    "BOOLEAN": TypeMapping("BOOLEAN", "BOOLEAN"),
    "TEXT": TypeMapping("TEXT", "TEXT"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "CLOB": TypeMapping("CLOB", "TEXT"),
    "BLOB": TypeMapping("BLOB", "BYTEA"),
    "DATE": TypeMapping("DATE", "DATE"),
    "DATETIME": TypeMapping("DATETIME", "TIMESTAMP"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TIMESTAMP"),
    "NULL": TypeMapping("NULL", "NULL"),
}

SQLITE_TO_MYSQL: dict[str, TypeMapping] = {
    "INTEGER": TypeMapping("INTEGER", "INT"),
    "INT": TypeMapping("INT", "INT"),
    "BIGINT": TypeMapping("BIGINT", "BIGINT"),
    "SMALLINT": TypeMapping("SMALLINT", "SMALLINT"),
    "TINYINT": TypeMapping("TINYINT", "TINYINT"),
    "REAL": TypeMapping("REAL", "FLOAT"),
    "FLOAT": TypeMapping("FLOAT", "FLOAT"),
    "DOUBLE": TypeMapping("DOUBLE", "DOUBLE"),
    "NUMERIC": TypeMapping("NUMERIC", "DECIMAL"),
    "DECIMAL": TypeMapping("DECIMAL", "DECIMAL"),
    "BOOLEAN": TypeMapping("BOOLEAN", "TINYINT(1)"),
    "TEXT": TypeMapping("TEXT", "TEXT"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "CLOB": TypeMapping("CLOB", "LONGTEXT"),
    "BLOB": TypeMapping("BLOB", "BLOB"),
    "DATE": TypeMapping("DATE", "DATE"),
    "DATETIME": TypeMapping("DATETIME", "DATETIME"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TIMESTAMP"),
    "NULL": TypeMapping("NULL", "NULL"),
}

SQLITE_TO_MARIADB: dict[str, TypeMapping] = SQLITE_TO_MYSQL

SQLITE_TO_MSSQL: dict[str, TypeMapping] = {
    "INTEGER": TypeMapping("INTEGER", "INT"),
    "INT": TypeMapping("INT", "INT"),
    "BIGINT": TypeMapping("BIGINT", "BIGINT"),
    "SMALLINT": TypeMapping("SMALLINT", "SMALLINT"),
    "TINYINT": TypeMapping("TINYINT", "TINYINT"),
    "REAL": TypeMapping("REAL", "REAL"),
    "FLOAT": TypeMapping("FLOAT", "FLOAT"),
    "DOUBLE": TypeMapping("DOUBLE", "FLOAT"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMERIC"),
    "DECIMAL": TypeMapping("DECIMAL", "DECIMAL"),
    "BOOLEAN": TypeMapping("BOOLEAN", "BIT"),
    "TEXT": TypeMapping("TEXT", "NVARCHAR(MAX)"),
    "VARCHAR": TypeMapping("VARCHAR", "NVARCHAR"),
    "CHAR": TypeMapping("CHAR", "NCHAR"),
    "CLOB": TypeMapping("CLOB", "NVARCHAR(MAX)"),
    "BLOB": TypeMapping("BLOB", "VARBINARY(MAX)"),
    "DATE": TypeMapping("DATE", "DATE"),
    "DATETIME": TypeMapping("DATETIME", "DATETIME2"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "DATETIME2"),
    "NULL": TypeMapping("NULL", "NULL"),
}

SQLITE_TO_ORACLE: dict[str, TypeMapping] = {
    "INTEGER": TypeMapping("INTEGER", "NUMBER(10)"),
    "INT": TypeMapping("INT", "NUMBER(10)"),
    "BIGINT": TypeMapping("BIGINT", "NUMBER(19)"),
    "SMALLINT": TypeMapping("SMALLINT", "NUMBER(5)"),
    "TINYINT": TypeMapping("TINYINT", "NUMBER(3)"),
    "REAL": TypeMapping("REAL", "BINARY_FLOAT"),
    "FLOAT": TypeMapping("FLOAT", "BINARY_FLOAT"),
    "DOUBLE": TypeMapping("DOUBLE", "BINARY_DOUBLE"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMBER"),
    "DECIMAL": TypeMapping("DECIMAL", "NUMBER"),
    "BOOLEAN": TypeMapping("BOOLEAN", "NUMBER(1)"),
    "TEXT": TypeMapping("TEXT", "CLOB"),
    "VARCHAR": TypeMapping("VARCHAR", "VARCHAR2"),
    "CHAR": TypeMapping("CHAR", "CHAR"),
    "CLOB": TypeMapping("CLOB", "CLOB"),
    "BLOB": TypeMapping("BLOB", "BLOB"),
    "DATE": TypeMapping("DATE", "DATE"),
    "DATETIME": TypeMapping("DATETIME", "TIMESTAMP"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TIMESTAMP"),
    "NULL": TypeMapping("NULL", "NULL"),
}

POSTGRES_TO_SQLITE: dict[str, TypeMapping] = {
    "INTEGER": TypeMapping("INTEGER", "INTEGER"),
    "INT": TypeMapping("INT", "INTEGER"),
    "INT4": TypeMapping("INT4", "INTEGER"),
    "BIGINT": TypeMapping("BIGINT", "BIGINT"),
    "INT8": TypeMapping("INT8", "BIGINT"),
    "SMALLINT": TypeMapping("SMALLINT", "INTEGER"),
    "BOOLEAN": TypeMapping("BOOLEAN", "INTEGER"),
    "REAL": TypeMapping("REAL", "REAL"),
    "FLOAT4": TypeMapping("FLOAT4", "REAL"),
    "DOUBLE PRECISION": TypeMapping("DOUBLE PRECISION", "REAL"),
    "FLOAT8": TypeMapping("FLOAT8", "REAL"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMERIC"),
    "DECIMAL": TypeMapping("DECIMAL", "NUMERIC"),
    "TEXT": TypeMapping("TEXT", "TEXT"),
    "VARCHAR": TypeMapping("VARCHAR", "TEXT"),
    "CHAR": TypeMapping("CHAR", "TEXT"),
    "BYTEA": TypeMapping("BYTEA", "BLOB"),
    "DATE": TypeMapping("DATE", "TEXT"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TEXT"),
    "TIMESTAMPTZ": TypeMapping("TIMESTAMPTZ", "TEXT"),
    "TIME": TypeMapping("TIME", "TEXT"),
    "SERIAL": TypeMapping("SERIAL", "INTEGER"),
    "BIGSERIAL": TypeMapping("BIGSERIAL", "INTEGER"),
    "UUID": TypeMapping("UUID", "TEXT"),
    "JSON": TypeMapping("JSON", "TEXT"),
    "JSONB": TypeMapping("JSONB", "TEXT"),
    "ARRAY": TypeMapping("ARRAY", "TEXT"),
}

MYSQL_TO_SQLITE: dict[str, TypeMapping] = {
    "INT": TypeMapping("INT", "INTEGER"),
    "INTEGER": TypeMapping("INTEGER", "INTEGER"),
    "BIGINT": TypeMapping("BIGINT", "INTEGER"),
    "SMALLINT": TypeMapping("SMALLINT", "INTEGER"),
    "TINYINT": TypeMapping("TINYINT", "INTEGER"),
    "TINYINT(1)": TypeMapping("TINYINT(1)", "INTEGER"),
    "FLOAT": TypeMapping("FLOAT", "REAL"),
    "DOUBLE": TypeMapping("DOUBLE", "REAL"),
    "DECIMAL": TypeMapping("DECIMAL", "NUMERIC"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMERIC"),
    "BIT": TypeMapping("BIT", "INTEGER"),
    "BOOL": TypeMapping("BOOL", "INTEGER"),
    "BOOLEAN": TypeMapping("BOOLEAN", "INTEGER"),
    "CHAR": TypeMapping("CHAR", "TEXT"),
    "VARCHAR": TypeMapping("VARCHAR", "TEXT"),
    "TEXT": TypeMapping("TEXT", "TEXT"),
    "MEDIUMTEXT": TypeMapping("MEDIUMTEXT", "TEXT"),
    "LONGTEXT": TypeMapping("LONGTEXT", "TEXT"),
    "BLOB": TypeMapping("BLOB", "BLOB"),
    "MEDIUMBLOB": TypeMapping("MEDIUMBLOB", "BLOB"),
    "LONGBLOB": TypeMapping("LONGBLOB", "BLOB"),
    "DATE": TypeMapping("DATE", "TEXT"),
    "DATETIME": TypeMapping("DATETIME", "TEXT"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TEXT"),
    "TIME": TypeMapping("TIME", "TEXT"),
    "YEAR": TypeMapping("YEAR", "INTEGER"),
    "ENUM": TypeMapping("ENUM", "TEXT"),
    "SET": TypeMapping("SET", "TEXT"),
    "JSON": TypeMapping("JSON", "TEXT"),
}

MARIADB_TO_SQLITE: dict[str, TypeMapping] = MYSQL_TO_SQLITE

MSSQL_TO_SQLITE: dict[str, TypeMapping] = {
    "INT": TypeMapping("INT", "INTEGER"),
    "BIGINT": TypeMapping("BIGINT", "INTEGER"),
    "SMALLINT": TypeMapping("SMALLINT", "INTEGER"),
    "TINYINT": TypeMapping("TINYINT", "INTEGER"),
    "BIT": TypeMapping("BIT", "INTEGER"),
    "FLOAT": TypeMapping("FLOAT", "REAL"),
    "REAL": TypeMapping("REAL", "REAL"),
    "DECIMAL": TypeMapping("DECIMAL", "NUMERIC"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMERIC"),
    "MONEY": TypeMapping("MONEY", "NUMERIC"),
    "SMALLMONEY": TypeMapping("SMALLMONEY", "NUMERIC"),
    "CHAR": TypeMapping("CHAR", "TEXT"),
    "NCHAR": TypeMapping("NCHAR", "TEXT"),
    "VARCHAR": TypeMapping("VARCHAR", "TEXT"),
    "NVARCHAR": TypeMapping("NVARCHAR", "TEXT"),
    "TEXT": TypeMapping("TEXT", "TEXT"),
    "NTEXT": TypeMapping("NTEXT", "TEXT"),
    "NVARCHAR(MAX)": TypeMapping("NVARCHAR(MAX)", "TEXT"),
    "VARCHAR(MAX)": TypeMapping("VARCHAR(MAX)", "TEXT"),
    "IMAGE": TypeMapping("IMAGE", "BLOB"),
    "VARBINARY": TypeMapping("VARBINARY", "BLOB"),
    "VARBINARY(MAX)": TypeMapping("VARBINARY(MAX)", "BLOB"),
    "DATE": TypeMapping("DATE", "TEXT"),
    "DATETIME": TypeMapping("DATETIME", "TEXT"),
    "DATETIME2": TypeMapping("DATETIME2", "TEXT"),
    "SMALLDATETIME": TypeMapping("SMALLDATETIME", "TEXT"),
    "TIME": TypeMapping("TIME", "TEXT"),
    "UNIQUEIDENTIFIER": TypeMapping("UNIQUEIDENTIFIER", "TEXT"),
    "XML": TypeMapping("XML", "TEXT"),
}

ORACLE_TO_SQLITE: dict[str, TypeMapping] = {
    "NUMBER": TypeMapping("NUMBER", "NUMERIC"),
    "NUMBER(10)": TypeMapping("NUMBER(10)", "INTEGER"),
    "NUMBER(19)": TypeMapping("NUMBER(19)", "INTEGER"),
    "NUMBER(5)": TypeMapping("NUMBER(5)", "INTEGER"),
    "NUMBER(3)": TypeMapping("NUMBER(3)", "INTEGER"),
    "NUMBER(1)": TypeMapping("NUMBER(1)", "INTEGER"),
    "BINARY_FLOAT": TypeMapping("BINARY_FLOAT", "REAL"),
    "BINARY_DOUBLE": TypeMapping("BINARY_DOUBLE", "REAL"),
    "FLOAT": TypeMapping("FLOAT", "REAL"),
    "VARCHAR2": TypeMapping("VARCHAR2", "TEXT"),
    "NVARCHAR2": TypeMapping("NVARCHAR2", "TEXT"),
    "CHAR": TypeMapping("CHAR", "TEXT"),
    "NCHAR": TypeMapping("NCHAR", "TEXT"),
    "CLOB": TypeMapping("CLOB", "TEXT"),
    "NCLOB": TypeMapping("NCLOB", "TEXT"),
    "BLOB": TypeMapping("BLOB", "BLOB"),
    "DATE": TypeMapping("DATE", "TEXT"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TEXT"),
    "RAW": TypeMapping("RAW", "BLOB"),
    "ROWID": TypeMapping("ROWID", "TEXT"),
}

FIREBIRD_TO_SQLITE: dict[str, TypeMapping] = {
    "SMALLINT": TypeMapping("SMALLINT", "INTEGER"),
    "INTEGER": TypeMapping("INTEGER", "INTEGER"),
    "BIGINT": TypeMapping("BIGINT", "INTEGER"),
    "FLOAT": TypeMapping("FLOAT", "REAL"),
    "DOUBLE PRECISION": TypeMapping("DOUBLE PRECISION", "REAL"),
    "DECIMAL": TypeMapping("DECIMAL", "NUMERIC"),
    "NUMERIC": TypeMapping("NUMERIC", "NUMERIC"),
    "VARCHAR": TypeMapping("VARCHAR", "TEXT"),
    "CHAR": TypeMapping("CHAR", "TEXT"),
    "BLOB SUB_TYPE TEXT": TypeMapping("BLOB SUB_TYPE TEXT", "TEXT"),
    "BLOB SUB_TYPE 0": TypeMapping("BLOB SUB_TYPE 0", "BLOB", warning="Campo binário — verificar conteúdo"),
    "BLOB": TypeMapping("BLOB", "BLOB", warning="Tipo binário — verificar conteúdo"),
    "DATE": TypeMapping("DATE", "TEXT"),
    "TIME": TypeMapping("TIME", "TEXT"),
    "TIMESTAMP": TypeMapping("TIMESTAMP", "TEXT"),
    "BOOLEAN": TypeMapping("BOOLEAN", "INTEGER"),
}

MAPPING_REGISTRY: dict[tuple[str, str], dict[str, TypeMapping]] = {
    ("firebird", "postgresql"): FIREBIRD_TO_POSTGRES,
    ("firebird", "mysql"): FIREBIRD_TO_MYSQL,
    ("firebird", "mariadb"): FIREBIRD_TO_MARIADB,
    ("firebird", "mssql"): FIREBIRD_TO_MSSQL,
    ("firebird", "oracle"): FIREBIRD_TO_ORACLE,
    ("mssql", "postgresql"): MSSQL_TO_POSTGRES,
    ("mssql", "mysql"): MSSQL_TO_MYSQL,
    ("mssql", "mariadb"): MSSQL_TO_MARIADB,
    ("mssql", "oracle"): MSSQL_TO_ORACLE,
    ("oracle", "postgresql"): ORACLE_TO_POSTGRES,
    ("oracle", "mariadb"): ORACLE_TO_MARIADB,
    ("oracle", "mssql"): ORACLE_TO_MSSQL,
    ("postgresql", "mssql"): POSTGRES_TO_MSSQL,
    ("postgresql", "mysql"): POSTGRES_TO_MYSQL,
    ("postgresql", "mariadb"): POSTGRES_TO_MARIADB,
    ("postgresql", "oracle"): POSTGRES_TO_ORACLE,
    ("sqlite", "postgresql"): SQLITE_TO_POSTGRES,
    ("sqlite", "mysql"): SQLITE_TO_MYSQL,
    ("sqlite", "mariadb"): SQLITE_TO_MARIADB,
    ("sqlite", "mssql"): SQLITE_TO_MSSQL,
    ("sqlite", "oracle"): SQLITE_TO_ORACLE,
    ("postgresql", "sqlite"): POSTGRES_TO_SQLITE,
    ("mysql", "sqlite"): MYSQL_TO_SQLITE,
    ("mariadb", "sqlite"): MARIADB_TO_SQLITE,
    ("mssql", "sqlite"): MSSQL_TO_SQLITE,
    ("oracle", "sqlite"): ORACLE_TO_SQLITE,
    ("firebird", "sqlite"): FIREBIRD_TO_SQLITE,
}
