from domain.entities import TypeMapping
from domain.interfaces import ColumnInfo, TableInfo
from domain.migration.type_maps import MAPPING_REGISTRY


class TypeConverter:
    def __init__(self, source_db_type: str, target_db_type: str):
        key = (source_db_type, target_db_type)
        self._mapping = MAPPING_REGISTRY.get(key)
        if self._mapping is None:
            raise ValueError(
                f"Nenhum mapeamento registrado para {source_db_type} → {target_db_type}"
            )
        self.source = source_db_type
        self.target = target_db_type

    def convert_column(self, column: ColumnInfo) -> TypeMapping:
        base = self._resolve_base_type(column.data_type)
        mapping = self._mapping.get(base)
        if mapping is None:
            return TypeMapping(
                source_type=column.data_type,
                target_type=column.data_type,
                warning=f"Tipo '{column.data_type}' não mapeado — mantido original",
            )
        return mapping

    def convert_table(self, table: TableInfo) -> list[dict]:
        result = []
        for col in table.columns:
            mapping = self.convert_column(col)
            result.append({
                "column": col,
                "mapping": mapping,
                "ddl_type": self._build_ddl_type(mapping, col),
                "has_conflict": self._has_conflict(mapping),
            })
        return result

    def detect_conflicts(self, table: TableInfo) -> list[dict]:
        conflicts = []
        for col in table.columns:
            mapping = self.convert_column(col)
            if self._has_conflict(mapping):
                conflicts.append({
                    "column": col,
                    "mapping": mapping,
                    "suggestions": self._suggest_types(col),
                })
        return conflicts

    def _resolve_base_type(self, data_type: str) -> str:
        upper = data_type.upper().strip()
        for sep in ("(", " "):
            idx = upper.find(sep)
            if idx > 0:
                upper = upper[:idx]
        return upper

    def _build_ddl_type(self, mapping: TypeMapping, column: ColumnInfo) -> str:
        ddl = mapping.target_type
        if mapping.conversion_expr:
            return ddl
        if column.char_length and ddl in ("VARCHAR", "CHAR", "NCHAR", "NVARCHAR", "VARBINARY", "RAW"):
            ddl = f"{ddl}({column.char_length})"
        elif column.precision is not None and ddl in ("DECIMAL", "NUMERIC", "NUMBER"):
            if column.scale is not None and column.scale > 0:
                ddl = f"{ddl}({column.precision},{column.scale})"
            elif column.precision:
                ddl = f"{ddl}({column.precision})"
        if column.is_identity:
            if self.target == "postgresql":
                ddl = ddl + " GENERATED BY DEFAULT AS IDENTITY"
            elif self.target in ("mysql", "mariadb"):
                ddl = ddl + " AUTO_INCREMENT"
            elif self.target == "sqlite":
                ddl = ddl + " AUTOINCREMENT"
        return ddl

    def _has_conflict(self, mapping: TypeMapping) -> bool:
        return mapping.warning is not None

    def _suggest_types(self, column: ColumnInfo) -> list[str]:
        base = self._resolve_base_type(column.data_type)
        if base == "NUMBER" and self.source == "oracle":
            return ["DECIMAL(38)", "BIGINT", "NUMERIC(38,8)"]
        if base == "BLOB":
            return ["BYTEA", "TEXT", "VARCHAR(8192)"]
        if base == "SQL_VARIANT":
            return ["TEXT", "JSON", "VARCHAR(MAX)"]
        return []
